baseURL = "https://seablock-challenge.netlify.com/"
languageCode = "ja-JP"
title = "Seablock Challenge"
theme = "story"
enableEmoji = true
uglyURLs = true
canonifyURLs = true

[permalinks]
  posts = "/:year/:month/:filename/"
[taxonomies]
  category = "categories"
  tag = "tags"